-- Mobile Dispatch START/FINISH evidence + per-order proof requirement.

ALTER TABLE dispatch_orders
  ADD COLUMN IF NOT EXISTS proof_required BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE dispatch_stops
  ADD COLUMN IF NOT EXISTS proof_required BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS start_phone_lat DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS start_phone_lon DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS start_armada_lat DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS start_armada_lon DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS complete_phone_lat DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS complete_phone_lon DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS complete_armada_lat DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS complete_armada_lon DOUBLE PRECISION NULL;
